version: '3'

services:
  redis:
    image: redis:5.0.4-alpine
    ports: 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data
  frontend:
    image: abiosoft/caddy
    ports:
      - '80:80'
      - '2015:2015'
      - '443:443'
    volumes:
      - ./frontend/dist:/srv/dist
      - ./frontend/Caddyfile:/etc/Caddyfile
      - ./.caddy:/root/.caddy
